name: Pandoc Document Converter

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: maxheld83/pandoc-action@v2
        with:
          args: "-s bits/*.md -o index.html"
