name: Pandoc Document Converter

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run:
          echo "::set-env name=FILELIST::$(printf '"%s" ' bits/*.md)"  
      - uses: maxheld83/pandoc-action@v2
        with:
          args: --output=index.html ${{ env.FILELIST }}
